siteTitle = "Node.uz онлайн ҳамжамияти"
siteDescr = "Node.js платформасида дастурлайдиган ўзбекзабон дастурчилар ҳамжамияти"
siteAuthor = "Node.uz"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

linkPrefix = "/node"
