siteTitle = "Node.uz онлайн ҳамжамияти"
siteDescr = "Node.js платформасида дастурлайдиган ўзбекзабон дастурчилар ҳамжамияти"
siteAuthor = "Node.uz"

siteTwitterUrl = "https://twitter.com/nodeuz"
siteGithubUrl = "https://github.com/nodeuz"
siteEmailUrl = "mailto:community@node.uz"

linkPrefix = "/node"
